# Generated by Django 3.1.7 on 2021-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default='https://example.com', max_length=500),
            preserve_default=False,
        ),
    ]
