# Generated by Django 3.1.7 on 2021-03-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210331_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
