# Generated by Django 3.1.7 on 2021-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20210331_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
