# Generated by Django 3.1.7 on 2021-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20210402_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
